var data = [
 {
   "codigo": 1,
   "nombre": "2pac - All Eyez On Me 2XLP",
   "ruta": "vinilos/2pac - All Eyez On Me 2XLP.jpg",
   "ano": 2017,
   "precio": 25,
   "formato": "XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "Originally recorded in 1996 and remastered in 2001, 2pac's fourth studio album All Eyez On Me is now available to own on 2-disc vinyl. Featuring the Billboard Hot 100 singles California Love + How Do U Want It, it was the last record the rapper released before his tragic passing. One of the most acclaimed hip-hop records of the 1990s, All Eyez On Me made history as the first double-full-length hip-hop solo studio album released for the mainstream. 2001, Death Row Records.",
   "referencia": "Product Sku: 43174564 ; Color Code: 001"
 },
 {
   "codigo": 2,
   "nombre": "Arcade Fire - Everything Now LP",
   "ruta": "vinilos/Arcade Fire - Everything Now LP.jpg",
   "ano": 2016,
   "precio": 21.8,
   "formato": "2XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "Everything Now is the fifth studio album by Arcade Fire and is now available here to own on vinyl. The Canadian indie rock band goes full-on disco, funk + dream-pop thanks to guest production by members of Daft Punk, Pulp + Portishead. Includes the singles Everything Now, Creature Comfort + Signs Of Life. 2017, Columbia Records.",
   "referencia": "Product Sku: 43798776 ; Color Code: 001"
 },
 {
   "codigo": 3,
   "nombre": "Beyonce - Lemonade 2XLP",
   "ruta": "vinilos/Beyonce - Lemonade 2XLP.jpg",
   "ano": 2015,
   "precio": 29,
   "formato": "XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "Lemonade, Beyonce's visual sixth studio album, is now available to own on premium 180 gram yellow vinyl. Spread across two discs with an included download card for the accompanying 60-minute film, Lemonade won countless music + film accolades and features the singles Formation, Sorry, Hold Up, Freedom + All Night. 2016, Parkwood Entertainment.",
   "referencia": "Product Sku: 43362540 ; Color Code: 072"
 },
 {
   "codigo": 4,
   "nombre": "Bob Dylan - The Essential Bob Dylan 2XLP",
   "ruta": "vinilos/Bob Dylan - The Essential Bob Dylan 2XLP.jpg",
   "ano": 1990,
   "precio": 49,
   "formato": "2XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "A compilation album, The Essential Bob Dylan is available here on 2-disc vinyl. Features songs from 1963's Blowin' In The Wind to 1999's Things Have Changed. An essential album for any Dylan fan, it's available here as a reissue. 2000, Columbia/Legacy.",
   "referencia": "Product Sku: 41517624 ; Color Code: 001"
 },
 {
   "codigo": 5,
   "nombre": "Bob Marley And The Wailers - Legend LP",
   "ruta": "vinilos/Bob Marley And The Wailers - Legend LP.jpg",
   "ano": 1989,
   "precio": 39,
   "formato": "XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "A reissue of the ultimate Bob Marley album, Legend contains 14 of Marley's greatest songs, serving as both a comprehensive introduction as well as a timeless tribute to a musical master. Easily the best-selling reggae album of all time, Legend includes 10 of Marley's 11 top 40 UK hits current to the time of pressing, plus three songs from an earlier configuration of the Wailers with Peter Tosh and Bunny Livingston. Available here on vinyl with the original full-color cover art. 1984, Island.",
   "referencia": "Product Sku: 24710550 ; Color Code: 001"
 },
 {
   "codigo": 6,
   "nombre": "Chuck Berry - Chuck LP",
   "ruta": "vinilos/Chuck Berry - Chuck LP.jpg",
   "ano": 1988,
   "precio": 19.9,
   "formato": "2XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "Now available to cherish on vinyl is Chuck Berry's last studio record featuring the rockin’-as-ever single Big Boys. Actively making music since the 1950s, Berry first announced Chuck's 2017 release on his 90th birthday, just weeks before passing away. The legendary musician who laid the groundwork for rock and roll, Berry was among the first musicians to be inducted into the Rock and Roll Hall of Fame upon its opening in 1986, is included on several of Rolling Stone's Greatest Of All Time lists + was elected to contribute the sole rock and roll song to the Voyager Golden Record - a condensed sampling of all of human culture intended for educational use by any extra-terrestrials that may find it! 2017, Dualtone Music Group.",
   "referencia": "Product Sku: 43191311 ; Color Code: 001"
 },
 {
   "codigo": 7,
   "nombre": "David Bowie - The Rise And Fall Of Ziggy Stardust And The Spiders From Mars LP",
   "ruta": "vinilos/David Bowie - The Rise And Fall Of Ziggy Stardust And The Spiders From Mars LP.jpg",
   "ano": 1977,
   "precio": 35,
   "formato": "XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "Based on the story of a fictional rock star named Ziggy Stardust, The Rise And Fall Of Ziggy Stardust And The Spiders From Mars is David Bowie's 5th studio album. Available here on high-quality 180g vinyl. 2016, Rhino/Parlophone.",
   "referencia": "Product Sku: 38888491 ; Color Code: 001"
 },
 {
   "codigo": 8,
   "nombre": "Fleetwood Mac - Rumours LP",
   "ruta": "vinilos/Fleetwood Mac - Rumours LP.jpg",
   "ano": 1975,
   "precio": 25,
   "formato": "2XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "Knuckle Puck's Shapeshifter album pressed to just 500 copies of limited edition yellow vinyl available only right here at UO! The second studio album from the Chicago pop-punk band features the single Gone and comes complete with an MP3 digital download card. 2017, Rise Records.",
   "referencia": "Product Sku: 44643567 ; Color Code: 072"
 },
 {
   "codigo": 9,
   "nombre": "Frank Sinatra - Songs for Swingin' Lovers! LP",
   "ruta": "vinilos/Frank Sinatra - Songs for Swingin' Lovers! LP.jpg",
   "ano": 1970,
   "precio": 21.8,
   "formato": "XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "Frank Sinatra's romantic masterpieces, arranged and conducted by Nelson Riddle. Originally released in 1956 and celebrating its 60th anniversary in 2016, Songs For Swingin' Lovers features classic standards and signature Sinatra recordings including I've Got You Under My Skin, Love Is Here To Stay and You Make Me Feel So Young. 2016, Capitol.",
   "referencia": "Product Sku: 38627998 ; Color Code: 001"
 },
 {
   "codigo": 10,
   "nombre": "Guns N' Roses - Appetite For Destruction LP",
   "ruta": "vinilos/Guns N' Roses - Appetite For Destruction LP.jpg",
   "ano": 2017,
   "precio": 29,
   "formato": "XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "The debut studio LP from the legendary Guns N' Roses, \"Appetite for Destruction\" was originally released in 1987. Available here on vinyl, because it's still completely amazing. 2008, Interscope.**",
   "referencia": "Product Sku: 29945730 ; Color Code: 001"
 },
 {
   "codigo": 11,
   "nombre": "HAIM - Something To Tell You Exclusive 2",
   "ruta": "vinilos/HAIM - Something To Tell You Exclusive 2.jpg",
   "ano": 2016,
   "precio": 49,
   "formato": "2XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "Now available here on 2-disc vinyl with UO-exclusive cover art is HAIM's second studio album, Something To Tell You. While the California sisters stick to their signature decades-past-influenced rock, pop + R&B rhythms, their second effort deepens emotionally, influenced by advice from Stevie Nicks to start keeping diaries. 2017, Columbia Records.",
   "referencia": "Product Sku: 44169860 ; Color Code: 001"
 },
 {
   "codigo": 12,
   "nombre": "Harry Styles - Harry Styles LP",
   "ruta": "vinilos/Harry Styles - Harry Styles LP.jpg",
   "ano": 2015,
   "precio": 39,
   "formato": "XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "The eponymous debut solo album from Harry Styles is now available right here on vinyl! Featuring the single Sign Of The Times, this is Styles' first solo release outside of band One Direction, featuring matured indie/pop-rock ballads tinged with spacey, psychedelic soul reminiscent of '70s Brit-rock. 2017, Erskine Records.",
   "referencia": "Product Sku: 43190297 ; Color Code: 001"
 },
 {
   "codigo": 13,
   "nombre": "John Williams - Raiders Of The Lost Ark Soundtrack 2XLP",
   "ruta": "vinilos/John Williams - Raiders Of The Lost Ark Soundtrack 2XLP.jpg",
   "ano": 1990,
   "precio": 19.9,
   "formato": "2XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "The Original Motion Picture Soundtrack from the first of the Indiana Jones movies is now available to own on 2-disc vinyl! Re-live the adventures of your favorite archaeologist over + over again with this epic score arranged by the most popular film composer of the modern era, John Williams, who created original music for some of the highest-grossing movies ever made including Star Wars, E.T., Jurassic Park + Harry Potter. 1981, Columbia.",
   "referencia": "Product Sku: 43290196 ; Color Code: 001"
 },
 {
   "codigo": 14,
   "nombre": "Kendrick Lamar - DAMN. 2XLP",
   "ruta": "vinilos/Kendrick Lamar - DAMN. 2XLP.jpg",
   "ano": 1989,
   "precio": 35,
   "formato": "XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "Now available on 180 gram vinyl is Kendrick Lamar's critically-acclaimed fourth studio album, DAMN. Earning the Grammy-nominated rapper his third consecutive number one record on US charts, he trades in the nuanced experimentation of To Pimp A Butterfly for a more direct approach, rapping furiously over samples of Fox News commentators criticizing him and Mike WiLL Made-It's minimalist trap beats. Featuring the singles HUMBLE., DNA. + LOYALTY. FEAT. RIHANNA., DAMN. is the work of an all-time great unapologetically in full command of his power. 2017, Top Dawg Entertainment.",
   "referencia": "Product Sku: 43862747 ; Color Code: 001"
 },
 {
   "codigo": 15,
   "nombre": "Kyle Dixon & Michael Stein - Stranger Things Original Series Soundtrack Vol. 1",
   "ruta": "vinilos/Kyle Dixon & Michael Stein - Stranger Things Original Series Soundtrack Vol. 1.jpg",
   "ano": 1988,
   "precio": 25,
   "formato": "2XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "Now available here on 2-disc vinyl is Vol. 1 of the original score to the Netflix series Stranger Things. Composed by Kyle Dixon and Michael Stein - otherwise known as the synth duo S U R V I V E - the score melds mysterious soundscapes with heavy synthesizers in an ode to '80s sci-fi + horror films. 2016, Lakeshore Records.",
   "referencia": "Product Sku: 43405810 ; Color Code: 095"
 },
 {
   "codigo": 16,
   "nombre": "Lady Gaga - Joanne 2XLP",
   "ruta": "vinilos/Lady Gaga - Joanne 2XLP.jpg",
   "ano": 1977,
   "precio": 21.8,
   "formato": "XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "The 5th studio album from Lady Gaga, Joanne is available here on 2-disc vinyl. Features production by Mark Ronson, Jeff Bhasker, BloodPop and RedOne, Gaga collaborated + co-produced most of the album. Moving away from the strictly dance-pop stylings of albums past, Joanne is \"stripped-down\" to showcase the singer's vocal talent. It is Gaga's 4th album to reach number 1 in the US. Package is a double gatefold with 2 standard weight black discs. 2016, Interscope.",
   "referencia": "Product Sku: 41809203 ; Color Code: 001"
 },
 {
   "codigo": 17,
   "nombre": "Lana Del Rey - Lust For Life Exclusive 2XLP",
   "ruta": "vinilos/Lana Del Rey - Lust For Life Exclusive 2XLP.jpg",
   "ano": 1975,
   "precio": 29,
   "formato": "2XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "Lana Del Rey's fifth studio album, Lust For Life, available exclusively at UO on coke bottle clear vinyl. Double LP set includes the singles Love and Lust For Life (feat. The Weeknd) as well as guest appearances by A$AP Rocky, Playboi Carti, Stevie Nicks + Sean Ono Lennon. Comes complete with a download link to the visual album. 2017, Interscope.",
   "referencia": "Product Sku: 44481497 ; Color Code: 100"
 },
 {
   "codigo": 18,
   "nombre": "Michael Jackson - Thriller LP",
   "ruta": "vinilos/Michael Jackson - Thriller LP.jpg",
   "ano": 1970,
   "precio": 49,
   "formato": "XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "Available here to cherish on vinyl is Michael Jackson's legendary Thriller album featuring the songs P.Y.T., Beat It, Wanna Be Startin' Somethin', Thriller, Billie Jean + more. Jackson's sixth studio record, Thriller is one of the world's best-selling albums to date, was the first US album to be certified platinum 33 times, won a record-breaking eight Grammy awards in 1984 + was the first musical project to successfully use music videos as a promotional tool with Thriller, Billie Jean + Beat It all receiving regular rotation on MTV. 1982, Epic Records.",
   "referencia": "Product Sku: 43513399 ; Color Code: 001"
 },
 {
   "codigo": 19,
   "nombre": "Oh Wonder - Ultralife Exclusive LP",
   "ruta": "vinilos/Oh Wonder - Ultralife Exclusive LP.jpg",
   "ano": 2017,
   "precio": 39,
   "formato": "XLP",
   "genero": "INDIE",
   "tipo": "VINILO",
   "descripcion": "Now available exclusively at UO on premium 180 gram clear vinyl is Oh Wonder's second studio album, Ultralife. The British duo crafts R&B-flecked synth-pop with singles like Ultralife, Lifetimes + My Friends. 2017, Island Records.",
   "referencia": "Product Sku: 43447135 ; Color Code: 100"
 },
 {
   "codigo": 20,
   "nombre": "Papa Roach - Infest LP",
   "ruta": "vinilos/Papa Roach - Infest LP.jpg",
   "ano": 2016,
   "precio": 19.9,
   "formato": "2XLP",
   "genero": "INDIE",
   "tipo": "VINILO",
   "descripcion": "Released in 2000, Infest is the second studio album by Papa Roach and is now available here on vinyl. Showcasing the band's boundary-pushing blend of alternative, metal + hip-hop influences, it earned them a Grammy nomination for best new artist and remains their best-selling album to date. Features the singles Last Resort, Between Angels and Insects, Broken Home + Dead Cell. 2000, DreamWorks.",
   "referencia": "Product Sku: 44617645 ; Color Code: 001"
 },
 {
   "codigo": 21,
   "nombre": "Paramore - After Laughter Limited LP",
   "ruta": "vinilos/Paramore - After Laughter Limited LP.jpg",
   "ano": 2015,
   "precio": 35,
   "formato": "XLP",
   "genero": "INDIE",
   "tipo": "VINILO",
   "descripcion": "Pressed on 2,000 copies of UO-exclusive orange and white vinyl, Paramore's fifth studio album, After Laughter, features the singles Hard Times and Told You So. A departure from their purely pop-punk sound of the past, After Laughter has been praised for symbolically contrasting lyrical themes of depression and anxiety with a slick, upbeat '80s synth-pop style reminiscent of Talking Heads, Paul Simon + the Bangles. Includes an MP3 digital download card. 2017, Fueled By Ramen.",
   "referencia": "Product Sku: 44127413 ; Color Code:"
 },
 {
   "codigo": 22,
   "nombre": "Queens Of The Stone Age - Villains 2XLP",
   "ruta": "vinilos/Queens Of The Stone Age - Villains 2XLP.jpg",
   "ano": 1990,
   "precio": 25,
   "formato": "2XLP",
   "genero": "INDIE",
   "tipo": "VINILO",
   "descripcion": "The eponymous debut solo album from Harry Styles is now available right here on vinyl! Featuring the single Sign Of The Times, this is Styles' first solo release outside of band One Direction, featuring matured indie/pop-rock ballads tinged with spacey, psychedelic soul reminiscent of '70s Brit-rock. 2017, Erskine Records.",
   "referencia": "Product Sku: 43190297 ; Color Code: 001"
 },
 {
   "codigo": 23,
   "nombre": "The Beatles - Abbey Road LP",
   "ruta": "vinilos/The Beatles - Abbey Road LP.jpg",
   "ano": 2017,
   "precio": 21.8,
   "formato": "XLP",
   "genero": "INDIE",
   "tipo": "VINILO",
   "descripcion": "**Overview:",
   "referencia": "Product Sku: 26748178 ; Color Code: 001"
 },
 {
   "codigo": 24,
   "nombre": "Various Artists - Baby Driver Soundtrack Exclusive 2XLP",
   "ruta": "vinilos/Various Artists - Baby Driver Soundtrack Exclusive 2XLP.jpg",
   "ano": 2016,
   "precio": 29,
   "formato": "2XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "The debut studio LP from the legendary Guns N' Roses, \"Appetite for Destruction\" was originally released in 1987. Available here on vinyl, because it's still completely amazing. 2008, Interscope.**",
   "referencia": "Product Sku: 43563303 ; Color Code: 001"
 },
 {
   "codigo": 25,
   "nombre": "Various Artists - Fifty Shades Darker Original Motion Picture Soundtrack 2XLP",
   "ruta": "vinilos/Various Artists - Fifty Shades Darker Original Motion Picture Soundtrack 2XLP.jpg",
   "ano": 2015,
   "precio": 25,
   "formato": "XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "The original score to the masterpiece San Junipero episode of the Netflix anthology series Black Mirror is here. Set in a retro-futuristic seaside town where a romance between two women seems to transcend space and time, the score by Clint Mansell (Requiem For A Dream) interweaves '80s electronica with strings for a nostalgic, orchestral ambience that you simply must see the episode to fully understand! Pressed to picture disc vinyl illustrated by comic pop art pioneer Butcher Billy. 2017, Invada/Lakeshore Records.",
   "referencia": "Product Sku: 44342871 ; Color Code: 095"
 },
 {
   "codigo": 26,
   "nombre": "Various Artists - Guardians Of The Galaxy Awesome Mix Vol. 2",
   "ruta": "vinilos/Various Artists - Guardians Of The Galaxy Awesome Mix Vol. 2.jpg",
   "ano": 1990,
   "precio": 21.8,
   "formato": "2XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "The second collection of songs featured in the Guardians of the Galaxy film, Awesome Mix Vol. 2 is now available here on 2-disc vinyl! Stacked with all the '70s hits that made the movie so especially memorable. 2014, Hollywood",
   "referencia": "Product Sku: 43803576 ; Color Code: 001"
 },
 {
   "codigo": 27,
   "nombre": "Various Artists - Kids Soundtrack LP",
   "ruta": "vinilos/Various Artists - Kids Soundtrack LP.jpg",
   "ano": 1989,
   "precio": 29,
   "formato": "XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "Original Motion Picture soundtrack from Larry Clark + Harmony Korrine's 1995 coming-of-age independent film, Kids. Put together by musician Lou Barlow, the soundtrack features multiple tracks from his lo-fi band Folk Implosion as well as other American indie-rock bands. Featuring four cover variants that are sent at random, the cover of the album you receive will be a total surprise! 1995, London Records.",
   "referencia": "Product Sku: 43285006 ; Color Code: 095"
 },
 {
   "codigo": 28,
   "nombre": "Various Artists - Pulp Fiction Music From The Motion Picture LP",
   "ruta": "vinilos/Various Artists - Pulp Fiction Music From The Motion Picture LP.jpg",
   "ano": 1988,
   "precio": 49,
   "formato": "XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "Eclectic, untraditional and unexpected, the Pulp Fiction soundtrack is available here on vinyl. A mix of surf music, American rock, pop and soul, this soundtrack features dialogue straight from the film. 2008, MCA Records.",
   "referencia": "Product Sku: 38528808 ; Color Code: 001"
 },
 {
   "codigo": 29,
   "nombre": "Various Artists - Singles Original Motion Picture Soundtrack 2XLP + CD",
   "ruta": "vinilos/Various Artists - Singles Original Motion Picture Soundtrack 2XLP + CD.jpg",
   "ano": 1975,
   "precio": 19.9,
   "formato": "XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "Now available to own in a 2-disc vinyl + CD deluxe box set is the Platinum-selling soundtrack to the 1992 film Singles. The movie centers around the fragile romantic lives of a group of teenagers in Seattle, Washington, featuring music by early, elemental Seattle grunge bands like Alice In Chains, Pearl Jam, Soundgarden, Mudhoney + Screaming Trees. Credited with first bringing the Seattle grunge scene to a mainstream audience, the Singles soundtrack was the catalyst that opened the door for the explosive, nation-wide grunge movement that would soon follow. 1992, Sony.",
   "referencia": "Product Sku: 43501915 ; Color Code: 001"
 },
 {
   "codigo": 30,
   "nombre": "Various Artists - The Perks Of Being A Wallflower Soundtrack LP",
   "ruta": "vinilos/Various Artists - The Perks Of Being A Wallflower Soundtrack LP.jpg",
   "ano": 1970,
   "precio": 35,
   "formato": "2XLP",
   "genero": "SOUNDTRACK",
   "tipo": "VINILO",
   "descripcion": "Music from The Perks of Being a Wallflower movie. Includes legendary classics from The Smiths, New Order XTC and others. Stephen Chbosky's coming-of-age book comes alive through this, the ideal soundtrack. 2012, Atlantic.",
   "referencia": "Product Sku: 26801639 ; Color Code: 001"
 },
 {
   "codigo": 31,
   "nombre": "Audio-Technica X UO AT-LP60 Bluetooth Vinyl Record Player 1",
   "ruta": "vinilos/tocadisco/Audio-Technica X UO AT-LP60 Bluetooth Vinyl Record Player 1.jpg",
   "ano": 1970,
   "precio": 169,
   "formato": "-",
   "genero": "-",
   "tipo": "TOCADISCO",
   "descripcion": "Bluetooth-compatible + fully automatic belt-driven turntable from Audio-Technica. Connects to wireless speakers, sound bars and headphones for an unforgettable listening experience, all with the high-quality performance you'd expect from Audio-Technica. Complete with both stereo phono and line-level pre-amp. Complete with two speeds - 33 1/3 and 45 rpm. To play outside of the US, please pair with a power converter.",
   "referencia": "Product Sku: 37762911 ; Color Code: 010"
 },
 {
   "codigo": 32,
   "nombre": "Crosley X UO Keepsake Wood Portable USB Vinyl Record Player 1",
   "ruta": "vinilos/tocadisco/Crosley X UO Keepsake Wood Portable USB Vinyl Record Player 1.jpg",
   "ano": 1970,
   "precio": 139,
   "formato": "-",
   "genero": "-",
   "tipo": "TOCADISCO",
   "descripcion": "Turn dusty vinyl LPs into digital gold with this vintage-inspired record player! This stylish turntable is easy to use and allows for deck and MP3 player integration. Built-in stereo speakers + diamond stylus needle for an awesome listening experience. Compatible with both MAC + PC operating systems and runs on 12 watts. To play outside of the US, please pair with a power converter. UO Exclusive.",
   "referencia": "Product Sku: 36421790 ; Color Code: 070"
 },
 {
   "codigo": 33,
   "nombre": "Crosley X UO Velvet Cruiser Bluetooth Record Player 1",
   "ruta": "vinilos/tocadisco/Crosley X UO Velvet Cruiser Bluetooth Record Player 1.jpg",
   "ano": 1970,
   "precio": 140,
   "formato": "-",
   "genero": "-",
   "tipo": "TOCADISCO",
   "descripcion": "Portable vintage-inspired turntable, totally exclusive to UO in Limited Edition velvet, from the experts at Crosley. This record player is perfect for playing your favorite vinyl LPs, and comes complete with everything you need for the ultimate vinyl experience. To play outside of the US, please pair with a power converter. UO Exclusive.",
   "referencia": "Product Sku: 43062116 ; Color Code: 041"
 },
 {
   "codigo": 34,
   "nombre": "EP-33 Bluetooth Turntable With Speakers - White",
   "ruta": "vinilos/tocadisco/EP-33 Bluetooth Turntable With Speakers - White.jpg",
   "ano": 1970,
   "precio": 159,
   "formato": "-",
   "genero": "-",
   "tipo": "TOCADISCO",
   "descripcion": "Play music through your Bluetooth-compatible device or listen to your favorite vinyl with this UO Exclusive record player + speakers! Design meets functionality with its sleek design and quality materials for a high quality listening experience. Only available at UO!",
   "referencia": "Product Sku: 39662812 ; Color Code: 010"
 },
 {
   "codigo": 35,
   "nombre": "Crosley T100 Turntable With Speakers",
   "ruta": "vinilos/tocadisco/Crosley T100 Turntable With Speakers.jpg",
   "ano": 1970,
   "precio": 122,
   "formato": "-",
   "genero": "-",
   "tipo": "TOCADISCO",
   "descripcion": "Turn up with Crosley's sleekly modern T100 turntable + speakers set that you can use to play vinyl or sync wirelessly to play music from any device! 2-speed turntable comes with two stereo speakers with built-in amps, adjustable pitch control + 30 watts of stereo power, offering super high-quality sound.",
   "referencia": "Product Sku: 43232321 ; Color Code: 046"
 },
 {
   "codigo": 36,
   "nombre": "Alina Barez - Electric Remix 12 EP",
   "ruta": "vinilos/Alina Barez - Electric Remix 12 EP.jpg",
   "ano": 2017,
   "precio": 39,
   "formato": "XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "In January Alina Baraz released Electric (feat. Khalid). Since the song's release it has been remixed by electro pop duo Marian Hill and Dutch producer R3hab. This limited edition 12\" EP pressed on translucent blue vinyl will feature the original track plus the remixes by Marian Hill and R3hab as well as three new remixes by unannounced artists! 2017, Mom + Pop.",
   "referencia": "Product Sku: 44128171 ; Color Code: 001"
 },
 {
   "codigo": 37,
   "nombre": "Gordi - Reservoir Limited LP + Bonus Flexi Disc",
   "ruta": "vinilos/Gordi - Reservoir Limited LP + Bonus Flexi Disc.jpg",
   "ano": 2016,
   "precio": 39,
   "formato": "XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "Now available exclusively through UO is Gordi's debut album Reservoir, limited to 500 vinyl copies with an included flexi disc full of bonus material. Hailing from a small rural town in Australia, singer-songwriter Gordi a.k.a. Sophie Payten layers electronica and folk. Gordi describes the \"reservoir\" as the place where her emotions can take hold and she can create her most honest art. Features the single Heaven I Know. 2017, Jagjaguwar.",
   "referencia": "Product Sku: 44337129 ; Color Code: 001"
 },
 {
   "codigo": 38,
   "nombre": "Mike WiLL Made-It - Ransom 2 2XLP",
   "ruta": "vinilos/Mike WiLL Made-It - Ransom 2 2XLP.jpg",
   "ano": 2015,
   "precio": 19.9,
   "formato": "2XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "The debut studio album by Atlanta trap producer Mike WiLL Made-It, Ransom 2 is now available here on 2-disc vinyl. From Beyonce's Formation and Rihanna's Pour It Up to Black Beatles by Rae Sremmurd and Humble by Kendrick Lamar, Mike Will has produced some of the most exciting trap-centric hits of recent times. On his follow up to 2014's Ransom mixtape, he employs the vocals of some of those same chart-topping artists like Rihanna and Kendrick while giving due attention to lesser known label mates like Andrea and Eearz. What results is an album full of his signature bangers all the way through. 2017, Eardruma Records.",
   "referencia": "Product Sku: 44292480 ; Color Code: 001"
 },
 {
   "codigo": 39,
   "nombre": "Portugal. The Man - Woodstock LP",
   "ruta": "vinilos/Portugal. The Man - Woodstock LP.jpg",
   "ano": 2017,
   "precio": 19.9,
   "formato": "2XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "Woodstock is the eighth studio album by Portugal. The Man and is now available here on premium 180-gram vinyl. Inspired by a conversation between lead singer John Gourley and his father and the discovery of a lost ticket stub from the Woodstock festival, it features catchy, psych-rock with guest production by Danger Mouse. Featuring the singles Noise Pollution, Number One + Feel It Still - the last of which peaked at number 1 on the Billboard Alternative Songs chart, becoming the band's first top 10 chart-topping song ever. Comes complete with an MP3 digital download card. 2017, Atlantic Records.",
   "referencia": "Product Sku: 44616480 ; Color Code: 001"
 },
 {
   "codigo": 40,
   "nombre": "Various Artists - The Nightmare Before Christmas Original Soundtrack 2XLP",
   "ruta": "vinilos/Various Artists - The Nightmare Before Christmas Original Soundtrack 2XLP.jpg",
   "ano": 2016,
   "precio": 35,
   "formato": "XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "Available now on 2-disc vinyl is the complete original soundtrack to Tim Burton's 1993 stop-motion film The Nightmare Before Christmas! Written and produced by Academy Award-nominated composer and long-time Burton collaborator Danny Elfman, who famously scored Batman and created The Simpson's theme song. Nominated for a Golden Globe award, The Nightmare Before Christmas soundtrack is full of theatrical but macabre songs perfect to sing along with the whole holiday season through - from Halloween to Christmas + beyond. 1993, Walt Disney.",
   "referencia": "Product Sku: 44619922 ; Color Code: 001"
 },
 {
   "codigo": 41,
   "nombre": "IT Original Motion Picture Score 2XLP",
   "ruta": "vinilos/IT Original Motion Picture Score 2XLP.jpg",
   "ano": 2015,
   "precio": 25,
   "formato": "2XLP",
   "genero": "HIP HOP",
   "tipo": "VINILO",
   "descripcion": "The complete 2-disc vinyl score to the 2017 cinematic re-make of Stephen King's 1986 horror novel starring the dreaded Pennywise the clown. Described by critics as one of the best King adaptations to date, IT was composed by award-winning Hollywood score-maker Benjamin Wallfisch, who combined classical orchestral elements, creepy old samples + intense moments of electronic hysteria to have you at the edge of your seat. 2017, WaterTower Music.",
   "referencia": "Product Sku: 44826592 ; Color Code: 001"
 },
 {
   "codigo": 42,
   "nombre": "Michael Jackson - SCREAM 2XLP",
   "ruta": "vinilos/Michael Jackson - SCREAM 2XLP.jpg",
   "ano": 1990,
   "precio": 21.8,
   "formato": "XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "A new 13-track complication of Michael Jackson's most dance-able horror-themed hits, pressed to glow-in-the-dark blue swirl vinyl and ready to play at your Halloween party! Featuring tracks like Thriller, Somebody's Watching Me + Blood On The Dance Floor, SCREAM reflects the king of pop's affection for Halloween's themes of costumes and disguise, dark and light, character transformations and surprise. Includes a hidden remixed mashup track by The White Panda. 2017, Legacy.",
   "referencia": "Product Sku: 44800423 ; Color Code: 040"
 },
 {
   "codigo": 43,
   "nombre": "Sam Hunt - 15 In A 30 Live Limited LP",
   "ruta": "vinilos/Sam Hunt - 15 In A 30 Live Limited LP.jpg",
   "ano": 1989,
   "precio": 29,
   "formato": "2XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "Live-recorded songs from Sam Hunt's 15 In A 30 tour, pressed to 2,500 limited edition copies of UO-exclusive clear 7\" vinyl. Includes live versions of his record-breaking country hit Body Like A Back Road as well as Ex To See.",
   "referencia": "Product Sku: 44928505 ; Color Code: 100"
 },
 {
   "codigo": 44,
   "nombre": "ABRA - ROSE Limited 2XLP",
   "ruta": "vinilos/ABRA - ROSE Limited 2XLP.jpg",
   "ano": 1988,
   "precio": 25,
   "formato": "XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "In a limited to 1,000 copy release on UO-exclusive rose pink vinyl is the album ROSE by singer, songwriter + producer ABRA. Hailed as the darkwave duchess of Atlanta's Awful Records, an otherwise rap crew, ABRA was raised in London, releasing ROSE via English record label Ninja Tune. Features the single Roses, which has over 3 million Spotify streams and was described as addictive by Dazed And Confused Magazine. 2017, Ninja Tune.",
   "referencia": "Product Sku: 44879674 ; Color Code: 066"
 },
 {
   "codigo": 45,
   "nombre": "Various Artists - NOW1s Limited 2XLP",
   "ruta": "vinilos/Various Artists - NOW1s Limited 2XLP.jpg",
   "ano": 1977,
   "precio": 21.8,
   "formato": "2XLP",
   "genero": "PUNK",
   "tipo": "VINILO",
   "descripcion": "Pressed in a limited release of 2,000 copies of UO-exclusive white vinyl, NOW #1s features 18 of the biggest chart-topping hits from the 2000-2010s. A perfect party playlist including Bruno Mars, Katy Perry, Pharrell Williams, Lil Wayne, Pitbull + many more. 2015, NOW.",
   "referencia": "Product Sku: 44630952 ; Color Code: 010"
 },
 {
   "codigo": 46,
   "nombre": "Niall Horan - Flicker Limited LP",
   "ruta": "vinilos/Niall Horan - Flicker Limited LP.jpg",
   "ano": 1975,
   "precio": 29,
   "formato": "XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "Pressed to just 5,000 limited edition copies of UO-exclusive clear blue vinyl (just like his eyes), the debut solo album by One Direction member Niall Horan is here. Horan develops his own sound, a classic rock-inspired blend of folk and pop, on singles like Slow Hands and This Town. 2017, Capitol Records.",
   "referencia": "Product Sku: 44905347 ; Color Code: 040"
 },
 {
   "codigo": 47,
   "nombre": "Brand New - Science Fiction Limited 2XLP",
   "ruta": "vinilos/Brand New - Science Fiction Limited 2XLP.jpg",
   "ano": 1970,
   "precio": 49,
   "formato": "XLP",
   "genero": "POP",
   "tipo": "VINILO",
   "descripcion": "Limited to just 5,000 copies on UO-exclusive clear double-disc vinyl is Brand New's fifth studio album, Science Fiction. Met with outstanding commercial success as it became Brand New's first number one album on the Billboard 200 chart ever, it's the band's first album release in 8 years since 2009's Daisy. 2017, Procrastinate! Music Traitors.",
   "referencia": "Product Sku: 44822146 ; Color Code: 100"
 },
 {
   "codigo": 48,
   "nombre": "Metallica - Hardwired... To Self-Destruct LP",
   "ruta": "vinilos/Metallica - Hardwired... To Self-Destruct LP.jpg",
   "ano": 1964.5,
   "precio": 60.47,
   "formato": "2XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "The 10th studio album from Metallica, Hardwired... To Self-Destruct is available here on vinyl. Their first album in 8 years, it is the first to not feature songwriting from Kirk Hammett. 2016, Rhino/Blackened Recordings.",
   "referencia": "Product Sku: 41312273 ; Color Code: 001"
 },
 {
   "codigo": 49,
   "nombre": "Soundgarden - Superunknown 2XLP",
   "ruta": "vinilos/Soundgarden - Superunknown 2XLP.jpg",
   "ano": 1959.4,
   "precio": 74.07,
   "formato": "XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "Soundgarden's 1994 breakthrough album, Superunknown, is now available here to own on 2-disc vinyl. Debuting at number one on the Billboard charts + winning the band two Grammy Awards, their fourth studio album marked a departure from their Seattle grunge scene roots to produce 15 tracks of arena-ready alternative rock. Includes the songs Spoonman, Black Hole Sun, The Day I Tried To Live, My Wave + Fell On Black Days. 1994, A&M Records.",
   "referencia": "Product Sku: 43591346 ; Color Code: 001"
 },
 {
   "codigo": 50,
   "nombre": "U2 - Joshua Tree LP",
   "ruta": "vinilos/U2 - Joshua Tree LP.jpg",
   "ano": 1954.3,
   "precio": 87.67,
   "formato": "XLP",
   "genero": "ROCK",
   "tipo": "VINILO",
   "descripcion": "U2's 2x Grammy award-winning Joshua Tree record on vinyl, digitally remastered from its original analogue recordings under the direction of The Edge. Features original album art and singles With or Without You, I Still Haven't Found What I'm Looking For + Where the Streets Have No Name. 2007, Mercury Records.",
   "referencia": "Product Sku: 42377515 ; Color Code: 001"
 }
]